### ISSUE TITLE
AudioSink usability

### ISSUE THREAD

**Issue by loic-fejoz** [FutureSDR/FutureSDR#111]
After discussion with @bastibl in #110 and in [fsdr-cli#6](https://github.com/loic-fejoz/fsdr-cli/pull/6#issuecomment-1493323547) I believe we should brainstorm a little bit on how to resolve the AudioSink topic.

Knowing that:
* FutureSDR aims at being _Fast: SDR go brrr!_
* leaky abstraction is to be avoided,
* it is expected that one develop his own program for a dedicated hardware.
* `fsdr-cli` is the exception of previous point (at the moment).
* a flow-graph is usually fixed in its expected number of channels (mono or stereo or ...).
*  `cpal` crate cannot handle a `StreamConfig` that does not match exactly the hardware. In particular,
   * audio rate,
   * number of channels
* rate adaptation could be done with `RationalResampler`
* mono to stereo adaptation could be done with `ApplyNM<1,2>` (but read again your textbooks). Similarly for greater number of channels (bass channel is it?).
* stereo to mono has no single answer and really depends on problem at hands, yet achievable with `Combine`.
* complexity of last 3 adaptations points has impact on performance:
   * better reducing audio rate than increasing,
   * better increasing channel (just copy) than reducing channel. 

The AudioSink API should aims at:
* providing feedback to help the developer on how to best adapt his flow-graph for his own hardware.
* ease automated decision on how to adapt the flow-graph.
* not leaking `cpal` crate.

Proposal is to have a first function that, given a device name, an expected audio rate, and expected channels, return a list of potential adaptation to apply sorted by least complexity. Something along:

```rust
impl AudioSink {
  pub fn propose_config(
      device_name: Into<String>,
      expected_channels: u16,
      expected_audio_rate: u32,
  ) -> Vec<ConfigProposal > {
   ...
  }
}
```

The `ConfigProposal` shall contains information on the adaptation to be done, and even better could be a builder of Block.

```rust
pub struct ResamplerBuilder {
  expected_audio_rate: u32,
  actual_audio_rate: u32,
  interpolation: u32,
  decimation: u32,
}

pub struct ChannelizerBuilder {
  expected_channels: u16,
  actual_channels: u16
}

pub struct ConfigProposal {
  resampler: Option<ResamplerBuilder>,
  channelizer: Option<ChannelizerBuilder>,
}

impl ResamplerBuilder  {
  pub fn build(self) -> Block {
    ...
  }
}

impl ChannelizerBuilder {
  pub fn build(self) -> Block {
    ...
  }
}
```

Overall it should allow the developer to know what to do and an automated program to easily adapt its flow-graph.
Open for discussion. What do you think? What is missing?

**Comment by bastibl** [comment]
You thought much more about this, but my gut felling would be that the main interface should be some `get_supported_configs` and  `get_supported_config_from_device`. And the constructor, accepting one of said configs.

Based on this, there may be some convenience functions, similar to the ones that you are suggesting. For example, to adapt one config to another config (e.g., mono to stereo conversion, resampling etc.). And maybe another function to get the config that is closest to your input config (similar to your `propose_config`). But this would all just be convenience functions. You could even have some functions that get the input block and flowgraph and add and connect the required blocks for adaption, in addition to the audio sink.

**Comment by loic-fejoz** [comment]
So it is pretty close to what I propose ...but forgot to mention.
Obviously the AudioSink constructor would be:

```rust
impl AudioSink {
  pub fn new(cfg: ConfigProposal) -> Block {
    ...
  }
}
```

Somehow it is mixing the basic interface and the convenience functions all at once.

If you prefer to align naming all in one could be:

```rust
pub struct ResamplerBuilder {
  expected_audio_rate: u32,
  interpolation: u32,
  decimation: u32,
}

pub struct ChannelizerBuilder {
  expected_channels: u16,
}

pub struct SupportedConfig {
  actual_audio_rate: u32,
  actual_channels: u16
}

impl SupportedConfig {
  pub fn get_resampler() -> Option<ResamplerBuilder> {...}
  pub fn get_channelizer() -> Option<ChannelizerBuilder> {...}
}

impl ResamplerBuilder  {
  pub fn build(self) -> Block {
    ...
  }
}

impl ChannelizerBuilder {
  pub fn build(self) -> Block {
    ...
  }
}

impl AudioSink {
  pub fn get_supported_configs(
      expected_channels: u16,
      expected_audio_rate: u32,
      device_name: Option<impl Into<String>>,
  ) -> Vec<SupportedConfig> {
   ...
  }

  pub fn new(cfg: SupportedConfig) -> Block {
    ...
  }
}

**Comment by bastibl** [comment]
Maybe I was mainly confused by the name of types, because I wouldn't add types for `ProposedConfig` or `SupportedConfig`. Shouldn't it be enough to just have a `AudioConfig` or `Config`. There is nothing in the type that guarantees that this config is supported. So `AudioSink::new(config: AudioConfig) -> Result<Block>` makes more sense than a `SupportedConfig` imho. Same for the `ProposedConfig`. To me  `AudioSink::new(config: ProposedConfig)` sounds like this are just suggestions that the constructor might do whatever it wants.

**Comment by loic-fejoz** [comment]
Let me try to explain differently... because I called `SupportedConfig` a configuration that is for sure supported by the hardware.

First case, required rate and channels' number match:
```rust
let some_cfgs_ordered_by_least_complexity = AudioSink::get_supported_configs(48_000, 2, None);
let cfg = some_cfgs_ordered_by_least_complexity[0];

// No need to adapt the flowgraph.
assert!(cfg.get_resampler().is_none());
assert!(cfg.get_channelizer().is_none());

let audio_blk = AudioSink::new(cfg);
```

Second case, required rate match but not the number of channels:
```rust
let some_cfgs_ordered_by_least_complexity = AudioSink::get_supported_configs(48_000, 1, Some("my_preferred_device"));
let cfg = some_cfgs_ordered_by_least_complexity[0]; // Or it could adapt another strategy

// Need to adapt the flowgraph.
assert!(cfg.get_resampler().is_none());
assert!(cfg.get_channelizer().is_some());
assert_eq!(cfg.actual_channels, 2);

// A program can automatically adapt the flowgraph
// with default: let adapter = cfg.get_channelizer().build();
// or build its own: let adapter = ApplyNM::<_, _, _, 1, 2>::new(....

// Next line will never fail but, without flowgraph adaptation, the sound will be speedy because the stream will be consumed by a stereo block
let audio_blk = AudioSink::new(cfg);
```

Lots of other cases could occurred. 😄 

But as you can understand, because of the way the `cfg` is created, the `AudioSink::new(cfg)` can never fail (thus it is a supported configuration). Yet a program has the information on how to adapt its own flow if needed.

What I don't like in the proposal: `AudioSink::new(config: AudioConfig) -> Result<Block>`, is that a program cannot know how to adapt the flowgraph. Just that the one requested as failed.

If you prefer to keep the current constructor  `AudioSink::new(sample_rate: u32, channels: u16) -> Block`, that is fine too as the same logic could be handled by helpers function too. I just believe we can contribute a nicer API that does not need one to import again the `cpal` crate.

What do you want to see in FutureSDR?
In any case, where do you prefer to implement those helpers? In FutureSDR? in fsdr-blockss?

**Comment by bastibl** [comment]
Just to make sure, I understand this correct: In this case, the config would remember internally, if it was created for a specific device? And when you construct the audio sink, using the config, it would check if it was created for a specific device?

My proposal was also to add a `get_supported_configs` call. An if you construct with a config that is not supported it will return an error (which is, in my opinion, anyway necessary (e.g. the device was disconnected etc.)) And that's the whole core, low-level API. Very simple and obvious.

Then, one could build the high-level API as you suggested. No strong feelings, if this high-level API would also be part of the `AudioSink`, or some utils. But this way, an app developer could build its own adaption strategy and wouldn't be forced to use the rather involved high-level API with channelizer etc.
