### ISSUE TITLE
choosing hackrf as device for examples?

### ISSUE THREAD

**Issue by RegEM** [FutureSDR/FutureSDR#120]
Hi Everyone,
Do I need to choose or set hackrf as my device for the examples?
I get an error, 
FutureSDR: ERROR - Source_0: Error during initialization. Terminating.
FutureSDR: ERROR - Source_0: Error in Block.run() Soapy (StreamError: RtAudio init error 'RtApiDs::probeDeviceOpen: error (Invalid parameter) creating input buffer (Default Device)!)
Richard

**Comment by RegEM** [comment]
I'll add that I'm on windows 10, and I can connect to my hackrf using CubicSDR.

**Comment by RegEM** [comment]
I guess I do have the other error,
←[1m←[33m[WARNING] SoapyVOLKConverters: no VOLK config file found. Run volk_profile for best performance.←[0m

**Comment by bastibl** [comment]
Soapy considers your sound card as SDR. Most applications have CLI parameters to select the soapy driver.
` cargo run --release --bin [...] -- -a soapy_driver=hackrf`

**Comment by RegEM** [comment]
Thanks Bastian. That works fine. 
I am receiving 'Seify Source Overflow' with the keyfob and adsb examples, but confirmed I'm headed in the right direction by connecting error free to the fm-receiver example.  Always nice to hear the sdr radio...
Cheers, Richard
