### ISSUE TITLE
Update wgpu depedency

### ISSUE THREAD

**Issue by klangner** [FutureSDR/FutureSDR#129]
Would it be possible to update dependency
```
wgpu = "0.19"
web-sys = "0.3.67"
```

I think pinning is not required now?

Currentlly it is not possible to compile this lib with other libraries which use newest version of web-sys (like iced)

**Comment by bastibl** [comment]
I updated the dependencies. Let me know, if this solves your problem.

**Comment by klangner** [comment]
Yes it does. Thank you!
