### ISSUE TITLE
Perhaps wrong license in LoRa examples

### ISSUE THREAD

**Issue by daniestevez** [FutureSDR/FutureSDR#145]
I was taking a look at the new LoRa examples and saw that the [LICENSE.txt](https://github.com/FutureSDR/FutureSDR/blob/main/examples/lora/LICENSE.txt) file is the GFDL v3, while the README says that the examples are GPLv3 because they're derived from a GPLv3 GNU Radio OOT module (which makes sense). So it seems that the wrong file was added as `LICENSE.txt`.

**Comment by bastibl** [comment]
Arg, sorry. I fixed it.
