### ISSUE TITLE
Instructions on how to start the frontend with FFT waterfall

### ISSUE THREAD

**Issue by mryndzionek** [FutureSDR/FutureSDR#15]
When I run `cargo run --example soapy --features="soapy"` it starts okay, but when I visit `http://127.0.0.1:1337/` I get `404: Not Found`. Are there more steps needed to start the frontend with the FFT waterfall? Running `make` in `frontend` subdirectory succeeds.

**Comment by bastibl** [comment]
If the frontend is built (with `make` and `./gulp`, as explained). It should be served by the normal Rocket server that also exposes control port. (Not really intuitive and not documented. Sorry.) That means if you run the example with the command you mentioned (`cargo run --example soapy --features="soapy"`) and enabled control port, i.e., in `config.toml` set
```toml
ctrlport_enable = true
ctrlport_bind = "127.0.0.1:1337"
```
the GUI should be available at `127.0.0.1:1337`. 

If this doesn't work, can you please provide a directory listing of `frontend/dist`?

**Comment by mryndzionek** [comment]
Okay, now it works. It's not that stable, sometimes hangs on `DEBUG - wait for blocks init` and waterfall stops updating, but when it works, it works :)

**Comment by bastibl** [comment]
Thanks for the heads-up! I'll close the issue, for now. If this deadlock/stall during startup turns out to be a bug. Please feel free to open a separate issue.
