### ISSUE TITLE
Bandwidth control in `Config` missing.

### ISSUE THREAD

**Issue by metasim** [FutureSDR/FutureSDR#156]
See: https://github.com/FutureSDR/FutureSDR/blob/60b31f4e9db28d164c131e44e39c7f18c5ed2fe3/src/blocks/seify/config.rs#L45-L47

Depends on: https://github.com/FutureSDR/seify/pull/13

**Comment by bastibl** [comment]
Should be added here: https://github.com/FutureSDR/FutureSDR/commit/a4a12a193c9db72c5d6373915f150669225e08d1
I don't usually set the bandwidth for the SDRs that I have available. Let me know, if there are any issues.
