### ISSUE TITLE
Feature request: MessageIO support in Mocker

### ISSUE THREAD

**Issue by metasim** [FutureSDR/FutureSDR#165]
`Mocker` simplifies the process of testing the StreamIO capabilities in new Blocks. Adding the ability to also test message handling with it would further assist the process.

**Comment by bastibl** [comment]
There's now an initial implementation. Let me know if this works for you. https://github.com/FutureSDR/FutureSDR/blob/main/tests/mocker.rs#L92-L107

**Comment by metasim** [comment]
Thanks!
