### ISSUE TITLE
Implicit assumption in `StreamIO` that buffer is fetched before tags. 

### ISSUE THREAD

**Issue by metasim** [FutureSDR/FutureSDR#171]
Assuming upstream `Block` generates `Tag`s, this fragment at the top of a `Kernel::work` implementation prints nothing:
```rust
sio.input(0).tags().iter().for_each(|t| {
    dbg!(t);
});
let input = sio.input(0).slice::<f32>();
```

While this prints tags as expected:
```rust
let input = sio.input(0).slice::<f32>();
sio.input(0).tags().iter().for_each(|t| {
    dbg!(t);
});
```

This is either a documentation issue or a minor bug, but mainly surprising until one figures it out. Logging it for awareness.

**Comment by bastibl** [comment]
Arg, good point. Thank you for bringing this up. Since you seem to have a test case ready, could you try adding this logic to the `tags()` function:

https://github.com/FutureSDR/FutureSDR/blob/main/src/runtime/stream_io.rs#L108-L118
