### ISSUE TITLE
wgpu dependency broken

### ISSUE THREAD

**Issue by lkolbly** [FutureSDR/FutureSDR#38]
Our current dependency is:
https://github.com/FutureSDR/FutureSDR/blob/9b047833a6b245a9a9e40b11ac8ceacfac458eb7/Cargo.toml#L101

However, wgpu recently pushed [b87e50feaed8cf02f71da34e284c3c2147ef5666](https://github.com/gfx-rs/wgpu/commit/b87e50feaed8cf02f71da34e284c3c2147ef5666), which renames the `adapter_downlevel_properties` function to `adapter_downlevel_capabilities`. Depending on the latest master means that updating (or regenerating) .lock files will pull this in, which will break the build (this is breaking the CI in #37).

A couple options that I can think of:
* Just fix our usage and leave the dependency how it is (the change doesn't seem to be functional),
* Change the dependency to a specific git commit, or
* Change it to depend on the `v0.12` git branch, or
* Depend only on the `0.12.0` version, which appears to have been released.

I'm not sure what the right fix is though.

**Comment by bastibl** [comment]
Arg :-/ AFAIS, wgpu is currently changing to a new shader format. Their idea was that v0.12 uses the old format and v0.13 switches to the new. But, it looks like some v0.12 backends already use the new one, which breaks the FutureSDR block. I just tested the `v0.12` branch, but it has the same issue. So, I'd suggest, we continue to track `master` until they release v0.13. Then, we can switch back to normal releases.

For now, I adapted the function name. I hope that they release 0.13 soon. If this continues to be an issue, we might need a better plan.
