### ISSUE TITLE
Only first TX/RX port can be used on soapy+usrp b210?

### ISSUE THREAD

**Issue by astrojhgu** [FutureSDR/FutureSDR#62]
https://github.com/FutureSDR/FutureSDR/blob/77f1a44f59847be85593eed3900b0294e44ea3eb/src/blocks/soapy_src.rs#L146

When getting stream from `soapydev`, the channel is hardcoded to 0.

**Comment by bastibl** [comment]
At this stage, the project is unfortunately full of those limitations. I didn't have the time to create a full-fledged block library but usually extend blocks as needed. Any help is greatly appreciated. Feel free to ask questions here or on Discord, if you want to give it a shot.

**Comment by etschneider** [comment]
I'm working on multi-channel support. It's currently working, but needs a little more polish. If you'd like to try it out, see:

https://github.com/etschneider/FutureSDR/tree/ets_soapy_multichan
