### ISSUE TITLE
Make SoapySource/Sink new() parameters optional

### ISSUE THREAD

**Issue by etschneider** [FutureSDR/FutureSDR#70]
Using the `dev` parameter allows for flexibility in preconfiguring a Soapy device, but the `freq`,`sample_rate`, and `gain` parameters are always applied, which may override the desired device settings.

I propose making those inputs `Option<>`.

A PR will follow shortly.

There are some other architecture questions I have about the Soapy implementation (and block/arch in general), perhaps the discussion area (Q&A?) might be the right place for that? 

For example, is `Kernel::init()` the mandated place for all device init, as opposed to doing it during creation of the block. It seems cleaner to me to init the device (and stream) in `new()` and just do the `stream.activate()` in `Kernel.init()`. That would alleviate the need to carry the initialization params in the sink/source struct, only to be used during flowgraph initialization.

**Comment by bastibl** [comment]
Thanks for the PR!

Regarding `init`: I agree that the code would be nicer, if this was done during creation of the block. However, in the future, it should be possible to stop, reconfigure, and restart a flowgraph. In that case, `init` would be run every time the flowgraph is (re)started. At least that was the idea when adding it.

Also Soapy and the underlying drivers might have uncommon constraints and `init` is run in the context of the thread that's running `work`. In case, a driver uses thread local storage, it would break things, if we opened in the constructor. (Thinking about this, that's yet another thing that the `dev` parameter breaks :-)).

Maybe, we should double-down on the builder pattern? Then we could keep the builders around and just create new blocks when we restart flowgraph?

As mentioned on Discord, my plan was anyhow to have serializable builders to allow straightforward flowgraph instantiation on remote hosts.
