### ISSUE TITLE
Add rustfmt.toml and clippy.toml files

### ISSUE THREAD

**Issue by etschneider** [FutureSDR/FutureSDR#93]
It would be nice to have a standard for the project styles and clippy checks enforced by CI.

E.g.: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity

**Comment by bastibl** [comment]
Since we check formatting and lints in CI, the implicit assumption is that we use the defaults for all settings. That's good enough for me. Also for the imports, I tend to use a mix of `Item` and `Module` and like it that way. Just not a big fan of `One` or `Crate`.

**Comment by etschneider** [comment]
Ok, just an idea to help with consistency.
